### ISSUE TITLE
The use of a 1 letter import is not good for the understanding of your code

### ISSUE THREAD

**Issue by damianveltkamp** [GiovanniKaaijk/web-app-from-scratch-1920#7]
You are importing a createElement function from your virtualdom component as h, this is not good for readability of your code.

https://github.com/GiovanniKaaijk/web-app-from-scratch-1920/blob/a775c3fc61714be78b3f3488595dcb09be7bc7b6/main.js#L5

**Comment by GiovanniKaaijk** [comment]
VueJS: Aliasing createElement to h is a common convention you’ll see in the Vue ecosystem and is actually required for JSX.
